name: base
channels:
  - conda-forge
  - bioconda
dependencies:
  - nodejs
  - upsetplot
  - seaborn
  - git
  - python
  - pybedtools
  - bedtools
  - xclip
  - conda[version='>=25.3.0']
  - mamba[version='>=2.1.1']
  - pip
  - ipython
  - pandas==2.3.3
  - numpy==2.3.5
  - matplotlib
  - pandoc
  - wkhtmltopdf
  - markdown
  - scipy
  - ipykernel
