name: base
channels:
  - conda-forge
  - bioconda
dependencies:
  - vim
  - tmux
  - nodejs
  - git
  - python
  - pybedtools
  - bedtools
  - xclip
  - conda[version='>=25.3.0']
  - mamba[version='>=2.1.1']
  - pip
  - ipython
  - pandas
  - matplotlib
  - pandoc
  - wkhtmltopdf
  - markdown
  - scipy
  - ipykernel
